resources:
  - kind: repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".name" # The Entity identifier will be the repository name.
          title: ".name"
          blueprint: '"service"'
          properties:
            readme: file://README.md # fetching the README.md file that is within the root folder of the repository and ingesting its contents as a markdown property
            url: .html_url
            defaultBranch: .default_branch
  - kind: file
    selector:
      query: 'true'
      files:
        - path: '**/package.json'
    port:
      itemsToParse: ".file.content.dependencies | to_entries"
      entity:
        mappings:
          identifier: ".item.key"
          title: '"_" + .item.key'
          blueprint: '"package"'
          properties:
            package: .item.key
            version: .item.value
          relations: {}
