resources:
  - kind: repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".name"
          title: ".name"
          blueprint: '"service"'
          properties:
            readme: file://README.md
            url: .html_url
            defaultBranch: .default_branch
  - kind: file
    selector:
      query: 'true'
      files:
        - path: '**/package.json'
    port:
      itemsToParse: ".file.content.dependencies | to_entries"
      entity:
        mappings:
          identifier: ".item.key"
          title: '"j" + .item.key'
          blueprint: '"package"'
          properties:
            package: .item.key
            version: .item.value
          relations: {}
