apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "aa"
  namespace: "org-bnedtwovpqxaa2vz"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    org_id: "org_BneDtWovPqXaA2VZ"
    integration_identifier: "aa"
    integration_id: "integration_4kQYNwwbBciZ9fhZ"
spec:
  project: ocean
  source:
    repoURL: 'git@github.com:port-labs/ocean-saas-common.git'
    path: charts/ocean-saas-chart-wrap
    targetRevision: "main"
    helm:
      parameters:
        - name: global.orgCredentialsSecretName
          value: "org-credentials-org-bnedtwovpqxaa2vz"
        # Secrets store serviceaccount Role ARN - will be created in ocean-saas-common terraform repository. Grants permissions to assume the secrets-store assumed role and tag the session while assuming the role.
        - name: global.secretStoreIRSAAssumedRoleArn
          value: "arn:aws:iam::000000000000:role/local-eu-west-1-secrets-store-irsa-role"
        # Secrets store assumed role ARN - will be created in port-tf terraform repository. Grants permissions to get the values from the secrets-store based on the session tags used in the assume function.
        # This role will be assumed in the initcontainer of the integrations jobs.
        - name: global.secretStoreAssumedRoleArn
          value: "arn:aws:iam::000000000000:role/local-eu-west-1-secrets-store-assumedrole-role"
        - name: global.region
          value: "eu-west-1"
        - name: global.orgId
          value: "org_BneDtWovPqXaA2VZ"
        - name: global.dynamodbTable
          value: "local-organization-secrets"
        - name: global.configNameToItemName.OCEAN__INTEGRATION__CONFIG__TOKEN_MAPPING
          value: "org_BneDtWovPqXaA2VZ/system/__GITLAB_AA_TOKEN_MAPPING"
        - name: ocean.integration.identifier
          value: "aa"
        - name: ocean.integration.type
          value: "gitlab"
        - name: ocean.integration.oauth.enabled
          value: "true"
        - name: ocean.scheduledResyncInterval
          value: "44 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
        - name: ocean.workload.cron.suspend
          value: "false"
        - name: ocean.port.baseUrl
          value: "http://localhost:3000"
        - name: ocean.extraLabels.portHost
          value: "localhost"
        - name: ocean.liveEvents.uuid
          value: "vE8CUVs79hHsrT86"
        - name: ocean.liveEvents.worker.enabled
          value: "false"
        - name: ocean.liveEvents.ingestHostname
          value: ""
        - name: ocean.liveEvents.extraConfig.OCEAN__BASE_URL
          value: "https:///live-events/vE8CUVs79hHsrT86"
        - name: ocean.integration.extraConfig.OCEAN__BASE_URL
          value: "https:///live-events/vE8CUVs79hHsrT86"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "org-bnedtwovpqxaa2vz"
