apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "dynatrace"
  namespace: "org-bnedtwovpqxaa2vz"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    org_id: "org_BneDtWovPqXaA2VZ"
    integration_identifier: "dynatrace"
    integration_id: "integration_qN7Up6YWwYpIBt2N"
spec:
  project: ocean
  source:
    repoURL: 'git@github.com:port-labs/ocean-saas-common.git'
    path: charts/ocean-saas-chart-wrap
    helm:
      parameters:
        - name: global.orgCredentialsSecretName
          value: "org-credentials-org-bnedtwovpqxaa2vz"
        - name: global.roleArn
          value: "arn:aws:iam::185657066287:role/staging-org_BneDtWovPqXaA2VZ-eu-west-1-secrets-store"
        - name: global.region
          value: "eu-west-1"
        - name: global.dynamodbTable
          value: "stg-01-organization-secrets"
        - name: global.configNameToItemName.OCEAN__INTEGRATION__CONFIG__DYNATRACE_API_KEY
          value: "org_BneDtWovPqXaA2VZ/global/_DYNATRACE_DYNATRACE_API_KEY"
        - name: ocean.integration.config.dynatraceHostUrl
          value: "http://dynatrace.com"
        - name: ocean.integration.identifier
          value: "dynatrace"
        - name: ocean.integration.type
          value: "dynatrace"
        - name: ocean.scheduledResyncInterval
          value: "31 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"
        - name: ocean.workload.cron.suspend
          value: ""
        - name: ocean.port.baseUrl
          value: "https://api.stg-01.getport.io"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "org-bnedtwovpqxaa2vz"
