apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "gitlab"
  namespace: "org-bnedtwovpqxaa2vz"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    org_id: "org_BneDtWovPqXaA2VZ"
    integration_identifier: "gitlab"
    integration_id: "integration_w8NyVOFYNWC7bO84"
spec:
  project: ocean
  source:
    repoURL: 'git@github.com:port-labs/ocean-saas-common.git'
    path: charts/ocean-saas-chart-wrap
    helm:
      parameters:
        - name: global.orgCredentialsSecretName
          value: "org-credentials-org-bnedtwovpqxaa2vz"
        - name: global.roleArn
          value: "arn:aws:iam::000000000000:role/local-org_BneDtWovPqXaA2VZ-eu-west-1-secrets-store"
        - name: global.region
          value: "eu-west-1"
        - name: global.dynamodbTable
          value: "local-organization-secrets"
        - name: global.configNameToItemName.OCEAN__INTEGRATION__CONFIG__TOKEN_MAPPING
          value: "org_BneDtWovPqXaA2VZ/global/_oauth2-gitlab-gitlab-tokenMapping"
        - name: ocean.integration.identifier
          value: "gitlab"
        - name: ocean.integration.type
          value: "gitlab"
        - name: ocean.scheduledResyncInterval
          value: "21 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"
        - name: ocean.workload.cron.suspend
          value: ""
        - name: ocean.port.baseUrl
          value: "http://localhost:3000"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "org-bnedtwovpqxaa2vz"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Retry=true
    retry:
      limit: 10
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 1m