apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "org-bnedtwovpqxaa2vz"
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: "org-bnedtwovpqxaa2vz"
  project: ocean
  source:
    path: "local/org_BneDtWovPqXaA2VZ"
    directory:
      exclude: "org-manifest.yml"
    repoURL: "git@github.com:omby8888/saas.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Retry=true
    retry:
      limit: 10
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 1m
